# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run the train and predict experiment.
#'
#' @param training_files A string vector. List of CSV filenames containing the training data.
#' @param test_files A string vector. List of CSV filenames containing the test data.
#' @param concrete_particles An integer scalar. The minimum number of particles per training sample. Default 100.
#' @param max_implicit_particles An integer scalar. The maximum number of particles per training sample. Default 1000.
#' @param target_ess An integer scalar. The minimum number of particles per test sample. Default 100.
#' @param max_em_iter An integer scalar. The maximum number of iterations for MCEM. Default 10.
#' @param max_lbfgs_iter An integer scalar. The maximum number of iterations for LBFGS. Default 100.
#' @param seed An integer scalar. The seed to use for the random number generator. Default 123.
#' @param tol A numerical scalar. The tolerance to use for the LBFGS minimizer. Default \eqn{1^{-10}}.
#' @param use_spf A logical scalar. Should we use a streaming particle filter process? Default TRUE.
#' @param parallelize A logical scalar. Should the experiment be run with parallelism? Default TRUE.
#' @export
train_and_predict <- function(training_files, test_files, concrete_particles = 100L, max_implicit_particles = 1000L, target_ess = 100L, max_em_iter = 10L, max_lbfgs_iter = 100L, seed = 123L, tol = 1e-10, use_spf = TRUE, parallelize = TRUE) {
    .Call(`_sgmwsmcpp_train_and_predict`, training_files, test_files, concrete_particles, max_implicit_particles, target_ess, max_em_iter, max_lbfgs_iter, seed, tol, use_spf, parallelize)
}

